### ISSUE TITLE
Ordenação de documentos por data de processamento e publicação

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#10]
A ordenação dos documentos deve ser feita por data de processamento e data de publicação, seguindo essa ordem de prioridade.

Os documentos devem aparecer em ordem decrescente, do mais atual para o mais antigo.

**Comment by carlosecbraga** [comment]
Corrigido por meio de alteração do arquivo de configuração do Solr.

**Comment by fabiobatalha** [comment]
Ola Carlos, por favor documentar no ticket que mudanças devem ser feitas no solr. Se essa correção foi feita no repósitório pulsemob-backoffice, por favor, fazer o pullrequest para nosso repositório.

**Comment by carlosecbraga** [comment]
@fabiobatalha a correção foi feita no nosso fork de pulsemob_solr. Existe um pull request pendente. Salvo engano, preciso que esse request seja aprovado antes de submeter outro.

**Comment by fabiobatalha** [comment]
@carlosecbraga Os pullrequests do pulsemob_webservices foram todos aceitos a aplicados no servidor.

**Comment by mateusalmeida** [comment]
@fabiobatalha, atualmente está sendo feito o que foi pedido?

**Comment by fabiobatalha** [comment]
@alexxxmendonca verificar com o @abelpacker se o look and feel e a ordenação estão ok.

**Comment by alexxxmendonca** [comment]
Não é possível validar esse ticket enquanto o #6 não for resolvido.

**Comment by alexxxmendonca** [comment]
Testado e aprovado.
