### ISSUE TITLE
Layout quebra ao editar busca.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#11]
Quando uma busca é feita utilizando a caixa de busca no topo do aplicativo, e o usuário clica no lápis para editar a busca, a interface do app  fica quebrada, ver imagem.

Problema detectado no IOS.

![img_1508](https://cloud.githubusercontent.com/assets/504142/12681839/b3ca7f76-c697-11e5-8c50-4c3e814681a6.PNG)

**Comment by fabiobatalha** [comment]
@amandasramalho

Por favor verificar se o mesmo acontece em android.

**Comment by amandasramalho** [comment]
@fabiobatalha 

O erro não acontece no Android. Testei na interface dos 3 idiomas.

**Comment by fabiobatalha** [comment]
@marcellus-sb Problema persiste

**Comment by mateusalmeida** [comment]
O erro persiste?

**Comment by fabiobatalha** [comment]
Corrigido.
