### ISSUE TITLE
Inserir texto "Resultado da busca" em EN e ES

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#12]
Ao realizar uma busca, a área onde seria exibido o texto "resultado" está em branco.

![screenshot_2016-01-29-15-13-07](https://cloud.githubusercontent.com/assets/5446933/12682555/2ef4ea80-c69b-11e5-9283-d961dab7a56c.png)

**Comment by mateusalmeida** [comment]
inseri esse texto e outros que estavam faltando, mas ainda não tenho o texto de boa vindas e a política da empresa. Essas traduções foram feitas por min e por isso tem que ser revisadas depois.

**Comment by fabiobatalha** [comment]
@mateusalmeida Ok.

Acompanhar o tickets #21 e #3 a definição dos textos será colocada nestes tickets.

**Comment by amandasramalho** [comment]
O texto continua não aparecendo.
![screenshot_2016-06-28-11-34-01](https://cloud.githubusercontent.com/assets/5446933/16419733/30b9ef86-3d25-11e6-921e-f56d1edcd52b.png)
![screenshot_2016-06-28-11-34-26](https://cloud.githubusercontent.com/assets/5446933/16419735/3325f86e-3d25-11e6-9dca-70322ac77f4d.png)

**Comment by mateusalmeida** [comment]
Adicionado o texto

**Comment by alexxxmendonca** [comment]
Testado e aprovado em Android e iOS.
