### ISSUE TITLE
Tela de boas-vindas sendo exibida ao entrar em "Preferências"

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#13]
Quando clicamos em "Preferências" a tela de "boas-vindas" está sendo exibida. Aparentemente isso acontece pq as duas opções no menu estão muito próximas.

**Comment by mateusalmeida** [comment]
Fiz a correção e aqui parou de ocorrer isto

**Comment by amandasramalho** [comment]
Testei hoje novamente e está tudo Ok! Parou de acontecer isso.
