### ISSUE TITLE
Traduzir tela de "Boas vindas" e definir imagem/vídeo da demonstração

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#2]
Na tela de "boas vindas" exibida quando incluímos um periódico na biblioteca, a informação está em  lorem ipsum e o vídeo exibido é do SciELO Livros.

**Comment by fabiobatalha** [comment]
Acompanhar em:

#3 Texto de boas vindas

#4 Video de entrada
