### ISSUE TITLE
Onde configurar integração com Webservices?

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#20]
Falta documentação de configuração do aplicativo.

**Comment by mateusalmeida** [comment]
copiei o leia-me do https://github.com/Infobase/pulsemob_app

tem uma seção que explica onde configurar

**Comment by fabiobatalha** [comment]
@mateusalmeida  O @leobueno corrigiu essa parte da documentação no dia 22 de março.

https://github.com/Infobase/pulsemob_app/commit/92e84e2d94c0afeadc947395665bf65bd6990587

Att.
