### ISSUE TITLE
Definir texto de políticas de uso.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#21]

**Comment by fabiobatalha** [comment]
PT
O aplicativo SciELO mobile permite o acesso livre e sem custos aos conteúdos da biblioteca de artigos científicos publicados pelas revistas da coleção SciELO (Scientific Electronic Library Online). Além da leitura online na tela de qualquer dispositivo ou offline de conteúdos descarregados, os artigos podem ser utilizados em diferentes produtos e serviços segundo o especificado nas atribuições da licença de Creative Commons específica de cada artigo. A responsabilidade dos conteúdos são dos respectivos autores dos artigos e dos editores da revistas onde foram publicados. O aplicativo SciELO Mobile é atualizado periodicamente após testes exaustivos. No entanto, o SciELO não responsabiliza pelas moléstias e danos que o aplicativo venha a causar.

**Comment by fabiobatalha** [comment]
@mateusalmeida os textos foram ajustados, falta a versão em inglês que será enviada em breve.

Português

O aplicativo SciELOMobile permite o acesso livre e sem custos aos conteúdos da biblioteca de artigos científicos publicados pelas revistas da coleção SciELO (Scientific Electronic Library Online). Além do acesso e leitura online os conteúdos podem ser descarregados em qualquer dispositivo. Os artigos podem ser utilizados em diferentes produtos e serviços segundo o especificado nas atribuições da licença de Creative Commons específica de cada artigo. A responsabilidade dos conteúdos é dos respectivos autores dos artigos e dos editores das revistas onde foram publicados. O aplicativo SciELOMobile é atualizado periodicamente após testes exaustivos. No entanto, o SciELO não se responsabiliza por problemas e danos que o aplicativo eventualmente venha a causar.

Espanhol

La aplicación SciELOMobile permite el acceso libre y gratuito a los contenidos de la biblioteca de artículos científicos publicados por las revistas de la colección SciELO (Scientific Electronic Library Online). Además del acceso y lectura online los contenidos pueden ser descargados en cualquier dispositivo. Los artículos pueden ser usados en diferentes productos y servicios según lo especificado en las atribuciones de la licencia Creative Commons específica de cada artículo. La responsabilidad de los contenidos es de los respectivos autores de los artículos y de los editores de las revistas donde fueron publicados. La aplicación SciELOMobile se actualiza periódicamente luego de pruebas exhaustivas. Sin embargo, SciELO no se responsabiliza por problemas y daños que la aplicación eventualmente pueda causar.

**Comment by alexxxmendonca** [comment]
Caros,

O texto foi alterado, favor considerar as versões abaixo.

**Português**
 
O aplicativo SciELOMobile permite o acesso livre e sem custos aos conteúdos da biblioteca de artigos científicos publicados por mais de 1000 revistas acadêmicas, revisadas por pares e operadas nas coleções nacionais dos 15 países da Rede SciELO (Scientific Electronic Library Online). Além do acesso e leitura online os conteúdos podem ser descarregados em qualquer dispositivo. Os artigos podem ser utilizados em diferentes produtos e serviços segundo o especificado nas atribuições da licença de Creative Commons específica de cada artigo. A responsabilidade dos conteúdos é dos respectivos autores dos artigos e dos editores das revistas onde foram publicados. Os usuários são responsáveis pelo uso do SciELOMobile. SciELO realiza todos os esfoços para assegurar o correto funcionamento do aplicativo e em nenhum caso se responsabiliza por problemas e danos que seu uso eventualmente venha a causar.
 
**Espanhol**

La aplicación SciELOMobile permite el acceso libre y gratuito a los contenidos de la biblioteca de artículos científicos publicados por más de 1000 revistas académicas, revisadas por pares y operadas en las colecciones nacionales de los 15 países de la Red SciELO (Scientific Electronic Library Online). Además del acceso y lectura online los contenidos pueden ser descargados en cualquier dispositivo. Los artículos pueden ser usados en diferentes productos y servicios según lo especificado en las atribuciones de la licencia Creative Commons específica de cada artículo. La responsabilidad de los contenidos es de los respectivos autores de los artículos y de los editores de las revistas donde fueron publicados. La aplicación SciELOMobile se actualiza periódicamente. Los usuarios son responsables por el uso de SciELOMobile. SciELO realiza todos los esfuerzos posibles para asegurar el correcto funcionamiento de la aplicación y en ningún caso se responsabiliza por problemas, fallas y daños que su uso eventualmente pueda causar.

**Inglês**

The SciELOMobile application allows unrestricted access, free of charge, to the contents of the library of scientific articles published in the over 1,000 academic, peer reviewed journals of the 15 countries in the SciELO (Scientific Electronic Library Online) network. In addition to online access and reading, contents can be downloaded to any device. The reuse of articles and their contents are governed by their corresponding Creative Commons Licenses. Responsibility for the contents rests with the corresponding authors and journal editors. The SciELOMobile application is updated periodically. Users accept all responsibility in the use of SciELOMobile. SciELO makes all reasonable efforts to ensure the proper functioning of SciELOMobile and in no event can be held responsible for any failures, damages or losses which might occur from its use.

**Comment by mateusalmeida** [comment]
Texto de políticas de uso adicionado ao repositório do projeto

**Comment by mateusalmeida** [comment]
@alexxxmendonca e @fabiobatalha, esse texto foi incorporado no aplicativo

**Comment by alexxxmendonca** [comment]
Ainda aparece o texto antigo, tanto no iOS quanto no Android.

![img_1862](https://cloud.githubusercontent.com/assets/4059679/18059877/80926752-6df1-11e6-976c-b106c464735d.PNG)

**Comment by alexxxmendonca** [comment]
Testado e aprovado.
