### ISSUE TITLE
Convite - Teste em SciELO Mobile

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/pulsemob_app#22]
15 de abril
Cara Javani,
Fiz alguns testes. O cadastro do operador funcionou direito.
Senti certa limitação para poder dimensionar as imagens como gostaria que ficassem. Com a capa por exemplo, não há como selecioná-la inteira mesmo alterando a dimensão da imagem pois a área de seleção limita sempre a mesma proporção da imagem independente de seu tamanho.
Qual o link para acessar com celular ou tablet? Tentei no site normal da revista no SciELO mas não houve mudança quando acessei os artigos para os quais inclui imagem de capa.
Abraço,
Sionei

**Comment by fabiobatalha** [comment]
O Aplicativo esta em fase de testes não sendo possível acessá-lo no momento.
O dimensionamento de imagens é limitado pois deve atender um padrão de tamalho.
