### ISSUE TITLE
Link para o texto completo acusando erro

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#23]
Ao acessar o artigo "A new species of Arapona from Peru (Hemiptera: Cicadellidae: Iassinae: Gyponini)" da revista "Zoologia (Curitiba)", cliquei em "Ir para o site" e apareceu a página abaixo.
![screenshot_2016-06-28-15-15-32](https://cloud.githubusercontent.com/assets/5446933/16427603/73ddbfa8-3d44-11e6-96ee-689e61d1d0a6.png)

**Comment by fabiobatalha** [comment]
Erro ocorre apenas em artigos que tiveram a imagem de capa trocada, quando a capa é removida o link para o artigo volta a funcionar.

**Comment by mateusalmeida** [comment]
Erro corrigido

**Comment by alexxxmendonca** [comment]
@mateusalmeida 

O erro persiste no Android e iOS.

**Comment by mateusalmeida** [comment]
A correção foi feita somente no ambiente de teste, o repositório no github, se for o caso do teste está sendo feito somente no aplicativo da loja.

**Comment by alexxxmendonca** [comment]
O teste foi feito no app da loja.

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Por favor, submeter um pullrequest desta correção para que possamos atualizar o App a partir de nosso repositório.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em aparelhos Android e iOS. Testado também após subir uma nova imagem em um outro artigo pelo backoffice.
