### ISSUE TITLE
Imagem de dentro do artigo está estourada

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#24]
A imagem de capa está estourando, ampliando demais, dentro do artigo.
![screenshot_2016-06-29-17-04-39](https://cloud.githubusercontent.com/assets/5446933/16467094/31acace2-3e1c-11e6-9427-85cc9c8dd0d1.png)
![screenshot_2016-06-29-17-04-43](https://cloud.githubusercontent.com/assets/5446933/16467096/333e3f80-3e1c-11e6-8da2-5c948c2a05c8.png)

**Comment by mateusalmeida** [comment]
Agora a imagem não está mais tão estourada

aqui está o exemplo de como está agora:

![screenshot_20160705-140334](https://cloud.githubusercontent.com/assets/10963190/16592958/8af41e6a-42b9-11e6-984f-1b1ab909c4cf.png)

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Enviar um pullrequest com essa correção para que possamos atualizar o app na loja para que os testes sejam realizados por nossa equipe.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em Android e iOS.
