### ISSUE TITLE
Aplicativo para de funcionar ao trocar idioma

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#25]
Ao trocar idioma sem settings o aplicativos para de funcionar.

**Comment by mateusalmeida** [comment]
Quando troca o idioma do celular, ou isso dentro do aplicativo mesmo?

**Comment by alexxxmendonca** [comment]
Dentro do app mesmo. Ele não trava mas várias funções deixam de funcionar.

**Comment by marcellus-sb** [comment]
Vocês podem passar um caso que esta acontecendo esse problema? Idioma e funcionalidade.

**Comment by alexxxmendonca** [comment]
Testei agora no iOS e não consegui reproduzir o erro. @fabiobatalha poderia testar?

**Comment by fabiobatalha** [comment]
@alexxxmendonca deve ter resolvido na última atualização.
