### ISSUE TITLE
Catalogo grande quebra aplicativo

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#26]
Quando o usuário possui uma lista grande de periódicos em seu catalogo e tentar utilizar o link "mais revistas" o aplicativo é fechado.

**Comment by fabiobatalha** [comment]
Não sei se a solução seria a mesma, mas em um caso o aplicativo fecha em outro o aplicativo fica aberto mas travado.

**Comment by mateusalmeida** [comment]
O erro ainda persiste na versão atual?

**Comment by alexxxmendonca** [comment]
Sim, persiste no iOS.

**Comment by alexxxmendonca** [comment]
Eu estava testando na versão antiga do app. Baixei a nova e o problema foi resolvido.

Testado em iOS e Android.
