### ISSUE TITLE
Erro ao remover um periódico de uma lista 

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#27]
Quando o usuário esta em uma lista de periódicos e clica na função de dispensar o periódico da lista, o aplicativo apresenta uma mensagem de erro.

![img_1723](https://cloud.githubusercontent.com/assets/504142/16534072/761fea68-3fb3-11e6-8191-069a05cd6024.PNG)

**Comment by alexxxmendonca** [comment]
Testei no Android e iOS e parece que foi corrigido.

@fabiobatalha, poderia testar novamente?

**Comment by fabiobatalha** [comment]
Parece ok o IOS.
