### ISSUE TITLE
Icone de preferidos não funciona.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#29]
O Icone de preferidos (coração) nos documentos não funciona, mostra mensagem de erro de conectividade.

**Comment by mateusalmeida** [comment]
Era um erro no servidor, foi feita uma alteração lá. Tem como atualizar e me falar para eu poder testar novamente.

**Comment by alexxxmendonca** [comment]
Testei no iOS e Android e me parece que foi corrigido.

**Comment by fabiobatalha** [comment]
Testei no IOS e funciona ao marcar como preferido. Ao desmarcar uma mensagem de erro é apresentada.

**Comment by mateusalmeida** [comment]
Esse erro pode ser corrigido pelo servidor. O Carlos Eduardo fez uma alteração no servidor há um tempo atrás, saberia se o servidor atual está rodando com esta mudança?

https://github.com/scieloorg/pulsemob_webservices/commit/2f24335575d8de162388ae58239e54713e5e58e3

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Sim, este é o código que esta no servidor.

**Comment by carlosecbraga** [comment]
Favor verificar se agora está resolvido.

**Comment by alexxxmendonca** [comment]
Necessário fazer alguma alteração? Atualizar o app? Pois o erro persiste no iOS.

**Comment by carlosecbraga** [comment]
Atualizar o server.

**Comment by fabiobatalha** [comment]
Testado e Ok.
