### ISSUE TITLE
Definir texto de boas vindas em PT, ES e EN.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#3]
O texto atual é um lorem ipsum.

**Comment by fabiobatalha** [comment]
Título

Pt - SciELO - Scientific Library
Es- SciELO - Biblioteca Científica
En- SciELO - Biblioteca Científica

Short description
Pt – Biblioteca de artigos das melhores revistas científicas do Brasil e países da Rede SciELO
Es– Biblioteca de artículos de las mejores revistas científicas de Ibero-América y África del Sur
En– Library of articles from the best Ibero-American and South African journals

Full description (4000 caracteres)
Pt
A biblioteca SciELO (Scientific Electronic Library Online) publica semanalmente mais de mil novos artigos das melhores revistas científicas do Brasil e demais países ibero-americanos e da África do Sul que comunicam resultados de pesquisas em ciências agrárias, biológicas, engenharias, exatas e da terra, humanas, literatura-letras-e-artes, saúde e sociais aplicadas. No todo, a biblioteca contém pouco mais de mil revistas e sobre 600 mil artigos.   

Es
La biblioteca SciELO (Scientific Electronic Library Online) publica semanalmente más de mil nuevos artículos de las mejores revistas científicas de los países iberoamericanos y de África del Sul que comunican resultados de investigación en ciencias de la agricultura, biológicas, ingenierías, exactas y  de la tierra, humanas, literatura-letras-y-artes, salud e sociales aplicadas. En total, la biblioteca abarca poco más de mil revistas y sobre 600 mil artículos.   

En
SciELO (Scientific Electronic Library Online) publishes weekly over one thousand new articles from the best iberoamerican journals and South Africa which communicate research results from the following scientific áreas: Agriculture, Biology, Exact and Earth, Health, Engineering, Social Sciences and Humanities. Overall, SciELO covers more than one thousand journals and over 600 thousand articles.

**Comment by fabiobatalha** [comment]
@abelpacker indicou que:

No welcome deve se juntar os três textos - titulo, primeiro parágrafo e descrição.

**Comment by mateusalmeida** [comment]
alterei o texto atual, verifique por favor se é para deixar no formato que está agora.

**Comment by scielo** [comment]
@mateusalmeida

Não consigo verificar uma vez que para isso o App deve ser atualizado na
loja. Existe alguma outra forma de testar?

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by mateusalmeida** [comment]
Me desculpe então, pensei que vocês também estivessem testando o aplicativo com o SDK do android, nesse caso quando atualizar o aplicativo na loja eu falo.

**Comment by scielo** [comment]
Ok Mateus.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-04-29 16:10 GMT-03:00 mateusalmeida <notifications@github.com>:

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Os textos devem ser modificados para:

[wellcome.pptx](https://github.com/scieloorg/pulsemob_app/files/245159/wellcome.pptx)

**Comment by mateusalmeida** [comment]
Você poderia me tirar uma dúvida sobre o texto de esclarecimento?

A ideia é colocar ele depois dos textos de boa vindas, ou você acha que seria melhor colocar ele antes? E se for escolhida a opção de 'não estou de acordo' seria para fechar o aplicativo.

**Comment by abelpacker** [comment]
Estou trabalhando com os seguintes conceitos e documentação para o português:

1. Nome - "SciELOMobile"

Descrições / Definições 

2. descritivo 1 - "SciELO - biblioteca científica" 
3. descritivo 2  - "Biblioteca de artigos das melhores revistas científicas do Brasil e países da Rede SciELO"
4. descritivo 3  - A biblioteca SciELO (Scientific Electronic Library Online) publica semanalmente mais de mil novos artigos das melhores revistas científicas do Brasil e demais países ibero-americanos e da África do Sul que comunicam resultados de pesquisas em ciências agrárias, biológicas, engenharias, exatas e da terra, humanas, literatura-letras-e-artes, saúde e sociais aplicadas. No todo, a biblioteca contém pouco mais de mil revistas e sobre 600 mil artigos.

Wellcome
5. Welcome 1 - slide1 do pptx
6. Welcome 2 - slide2 do pptx
7. Wecome 3 - slide3 do ppts

Política de uso
8. O aplicativo SciELOMobile permite o acesso livre e sem custos aos conteúdos da biblioteca de artigos científicos publicados pelas revistas da coleção SciELO (Scientific Electronic Library Online). Além do acesso e leitura online os conteúdos podem ser descarregados em qualquer dispositivo. Os artigos podem ser utilizados em diferentes produtos e serviços segundo o especificado nas atribuições da licença de Creative Commons específica de cada artigo. A responsabilidade dos conteúdos é dos respectivos autores dos artigos e dos editores das revistas onde foram publicados. O aplicativo SciELOMobile é atualizado periodicamente após testes exaustivos. No entanto, o SciELO não se responsabiliza por problemas e danos que o aplicativo eventualmente venha a causar.

Entendo que o nome do aplicativo é o que aparece nas listas. O descritivo 1 é o subtítulo etc

O Welcome aparece na primeira vez que o aplicativo é carregado.

A política de uso deve ser mostrada no momento da instalação.

No menu do sistema deverá vir também um entrada Welcome e Política de para o usuário recuperar os textos.

**Comment by mateusalmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/10963190/14965756/760a4972-1085-11e6-925f-e94626cbe225.png)

A ideia é tirar esse vídeo e colocar o logo da SciELO maior, ou deixar o vídeo?

E sobre o texto de Esclarecimento, qual é o melhor lugar para colocar ele?

**Comment by abelpacker** [comment]
Olá. Desculpem-me. Mas,  como posso ver o vídeo para opinar?

Qual texto é o "texto de esclarecimento" ?

**Comment by mateusalmeida** [comment]
Esse texto está dentro do arquivo wellcome.pptx enviado pelo fabiobatalha.

**Comment by abelpacker** [comment]
Penso que pode ser um texto que foi preparado para a carga de imagens? Caso
sim, não se aplica no lado público do app.

Vc pode enviar o texto para eu verificar?

Abel
On May 2, 2016 4:57 PM, "mateusalmeida" <notifications@github.com> wrote:

Esse texto está dentro do arquivo wellcome.pptx enviado pelo fabiobatalha.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/scieloorg/pulsemob_app/issues/3#issuecomment-216344247>

**Comment by mateusalmeida** [comment]
Esclarecimento​
​
Os conteúdos publicados pelos periódicos indexados no SciELO, sejam os textos e imagens de artigos ou de capas de números são disponibilizados online em Acesso Aberto. Cabe a cada periódico adotar um dos tipos de licenças de acesso e de uso dos conteúdos entres as opções recomendadas pelo SciELO e oferecidas pelo sistema de licenças do Creative Commons.​
​
O usuário que acessa ou faz downloads de conteúdos dos artigos ou da capas de um periódico deve obedecer as restrições de uso estabelecidas pelas atribuições de acesso e uso adotadas pelos periódico. ​
​
A responsabilidade sobre o direito de disponibilizar os conteúdos e as capas segundo a licença do Creative Commons adotada é do autor ou autores do artigos e do editor do periódico inclusive sobre o uso de conteúdos de terceiros. Não cabe ao SciELO nenhuma responsabilidade sobre qualquer uso indevido de qualquer tipo de conteúdos inclusive de imagens.​
​
Ao prosseguir com o meu registro para disponibilizar imagens para a disseminação de artigos e números de periódicos para o aplicativo SciELO Mobile manifesto que estou ciente das condições acima.  ​
​
                                               [não estou de acordo]  [ estou de acordo ]

**Comment by abelpacker** [comment]
Mateus

Este texto se aplica no aplicativo de carga de imagens.

Não se aplica na interface e tampouco na loja.

Abel
