### ISSUE TITLE
Msg inicial - mudar para

### ISSUE THREAD

**Issue by abelpacker** [scieloorg/pulsemob_app#32]
SciELOMobile 
-	Msg inicial: You need to define a list of journals to start

**Comment by mateusalmeida** [comment]
Mudei também a mensagem em português e espanhol. 

antes estava:

en: You do not have any list of configured papers.
pt: Você ainda não possui nenhuma lista de periódicos configurada.
es: Usted no tiene ninguna lista de periódicos configurados.

agora está:

en: You need to define a list of journals to start.
pt: Você precisa definir uma lista de periódicos de começar.
es: Usted necesita definir la lista de periódicos para empezar.

**Comment by alexxxmendonca** [comment]
Corrigir para 

pt: Você precisa definir uma lista de periódicos para começar.

**Comment by mateusalmeida** [comment]
Correção feita

**Comment by alexxxmendonca** [comment]
Testado e aprovado em iOS e Andoid.
