### ISSUE TITLE
Após msg inicial App para 

### ISSUE THREAD

**Issue by abelpacker** [scieloorg/pulsemob_app#33]
-	Ao clicar “Start now” o app para com a tela em branco 
-

**Comment by mateusalmeida** [comment]
Em qual plataforma acontece esse erro?

**Comment by abelpacker** [comment]
Android

Em quinta-feira, 7 de julho de 2016, mateusalmeida <notifications@github.com>
escreveu:

**Comment by alexxxmendonca** [comment]
Esse erro foi notado também no iOS em um iPhone 6s.

**Comment by mateusalmeida** [comment]
Poderia testar de novo e falar se o erro persiste?

**Comment by alexxxmendonca** [comment]
Após essa última atualização o problema foi aparentemente resolvido.

@abelpacker poderia testar?

**Comment by abelpacker** [comment]
Não funciona. OS - Android 6.0.1, ao clicar Login with Google o sistema fica parado e após um bom tempo (quase um minuto) aparece a msg: Não foi possível realizar a autenticação. Por favor verifique a conexão com a internet e tente novamente. A conexão com a Internet está operando regularmente, com signal strength -50dBm.

**Comment by alexxxmendonca** [comment]
@abelpacker certifique-se de que você tem instalada a versão mais recente (1.0.12).

**Comment by abelpacker** [comment]
Sim. Repeti nova instalação e diferentes emails do Google e não funciona.

**Comment by leobueno** [comment]
Abel, por favor informe o modelo do seu celular e a versão do sistema operacional nele instalado para tentarmos reproduzir o problema.

**Comment by abelpacker** [comment]
Nexus 6P, Android 6.0.1

**Comment by mateusalmeida** [comment]
@abelpacker, na nova versão ainda ocorre esse erro?

**Comment by alexxxmendonca** [comment]
O problema foi resolvido ao baixar a nova versão do app.
