### ISSUE TITLE
Aplicativo fecha quando lista de periódicos é muito grande.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#34]

**Comment by leobueno** [comment]
Seria o mesmo que o #26 ?

**Comment by mateusalmeida** [comment]
Atualmente carrega-se 4 listas de feed por vez para evitar esse erro

**Comment by alexxxmendonca** [comment]
O erro persiste. Fiz uma lista com todos os periódicos e ao clicar em "Mais em...", o app fecha.

Testado em iOS.

**Comment by alexxxmendonca** [comment]
Eu estava testando na versão antiga do app. Baixei a nova e o problema foi resolvido.

Testado em iOS e Android.
