### ISSUE TITLE
SciELOMobile não parte no Android 

### ISSUE THREAD

**Issue by abelpacker** [scieloorg/pulsemob_app#35]
A aplicação nao parte. Recarreguei hoje 13/7. Após login via Google email, fica parado.  Ao tocar o ícone SciELO informa que não foi possível realizar a autenticação. Verifique conexão e tente novamente. Estou em rede local operando corretamente com outras aplicações.

**Comment by fabiobatalha** [comment]
@abelpacker 

Com essas indicações aparentemente o problema esta relacionado a autenticação através do Google.

A Autenticação por Facebook esta funcionando. Esse teste foi feito ontem com @marcellus-sb que se autenticou sem problema com Facebook.

Vamos realizar outros testes para validar esta hipotese.

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

Veja com o Abel se ainda ocorre.

**Comment by alexxxmendonca** [comment]
Testei com o @abelpacker, com a versão mais atual e o comportamento ainda está estranho. Não acontece nada após escolher a opção de fazer o login via Google. Foi possível se conectar apenas via Facebook.

O teste foi feito em um Android.

**Comment by marcellus-sb** [comment]
Boa tarde pessoal,

Caso vocês estejam utilizando a versão mais recente do plugin do google+ a assinatura dos metodos foram alteradas. Quando o projeto foi desenvolvido o plugin estava na versão 4.x.x, para utilizar a versão 5.x.x é necessário alguns ajustes que fizemos.

Já fiz o pull request para utilizar a versão mais recente do plugin.

**Comment by alexxxmendonca** [comment]
O problema persiste.

**Comment by mateusalmeida** [comment]
Acredito que não foi gerada a versão do aplicativo com a correção, pois a solução ainda se encontra no pull request.

**Comment by fabiobatalha** [comment]
@mateusalmeida a correção foi aplicada por meio de patch do pull request.

**Comment by alexxxmendonca** [comment]
@mateusalmeida 

Já podemos testar isso novamente ou o app precisa ser atualizado?

**Comment by mateusalmeida** [comment]
@alexxxmendonca não sei dizer se o aplicativo que está na loja já possui essa correção, pois não sou eu quem está gerando o mesmo. Acredito que seria bom aplicar algumas correções que eu já enviei e gerar novamente o aplicativa, para que se possa testar mais coisas.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em iOS e Android.
