### ISSUE TITLE
Aumentar a largura das caixas dos artigos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/pulsemob_app#44]
Atualmente aparecem 3 caixas de artigos em cada fileira: 2 caixas inteiras e 3/4 da terceira caixa.

Aumentar a largura das caixas, deixando à mostra 2 caixas inteiras e 1/4 da terceira caixa.

**Comment by mateusalmeida** [comment]
qual o modelo do celular que foi usando quando se observou isso?

**Comment by alexxxmendonca** [comment]
Nexus 6P e iPhone 6S

**Comment by mateusalmeida** [comment]
Isso aconteceu por causa que esses celulares tem uma resolução maior que a média dos outros, vou colocar para aumentar os elementos nesse caso.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em iOS e Android.
