### ISSUE TITLE
Contextualizar filtros por Coleção SciELO

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/pulsemob_app#45]
Incluir um filtro por Coleção SciELO no topo da relação de filtros de forma que, os filtros subsequentes sejam exibidos de acordo com a Coleção SciELO definida pelo usuário.

![img_2424](https://cloud.githubusercontent.com/assets/4059679/19076467/46e64984-8a1f-11e6-810e-16a8b5680f0f.PNG)

Ex: ao escolher "SciELO Brasil", exibir somente periódicos dessa Coleção ao clicar na letra "A".

**Comment by alexxxmendonca** [comment]
Isso havia sido implantado na versão anterior, embora não estava funcionando corretamente, mas na versão atual (1.0.22) já não está mais disponível.

**Comment by mateusalmeida** [comment]
Não está mais aparecendo a parte de seleção de coleção você diz?

A última versão que eu vi aqui era a 1.0.21 e realmente tinha. @fabiobatalha você sabe me dizer se a última versão que você gerou tem algo diferente da anterior, ou possa ter alguma motivo de não estar aparecendo agora?

**Comment by alexxxmendonca** [comment]
Sim, não dá mais para escolher o país. Antes dava.

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Não fizemos mudanças na aplicação, vocês são os únicos que comitam códigos. A única mudança que faço é nos arquivos .sh de geração de pacotes, e as vezes no readme.

**Comment by alexxxmendonca** [comment]
O filtro não funciona na v.1.0.23. Mesmo selecionando "Brasil", a lista de periódicos mostra títulos de outras coleções.

**Comment by mateusalmeida** [comment]
@alexxxmendonca poderia dar um exemplo por favor, para eu verificar.

**Comment by alexxxmendonca** [comment]
![img_3905](https://cloud.githubusercontent.com/assets/4059679/22016886/01f450c4-dc8f-11e6-966d-7f183b62165a.PNG)

"Acción Psicologia"  não faz parte da Coleção Brasil.

**Comment by mateusalmeida** [comment]
@alexxxmendonca eu não consegui reproduzir esse erro, aqui essa "Acción Psicologia" só apareceu depois que eu selecionei o filtro de coleção Spain. O que pode ter ocorrido é que, depois de selecionar os filtros desejados ir para uma outra tela e voltar para a tela de selecionar os filtros, todos os filtros vão estar selecionados novamente. Eu fiz uma modificação para que isso não ocorra, assim os filtros não vão se auto selecionar mais e o estado dos filtros selecionados irá ser mantido.

**Comment by alexxxmendonca** [comment]
O erro persiste, mesmo na v1.0.24

Após escolher "Brasil" eu não tenho escolha senão escolher as áreas. Nesse caso, escolho todas as áreas e após dar o nome na lista, aparecem periódicos de outros países diferentes do Brasil.

**Comment by mateusalmeida** [comment]
@alexxxmendonca poderia testar de novo quando a próxima versão do aplicativo for gerada.

**Comment by alexxxmendonca** [comment]
Testado e aprovado na v.1.0.25
