### ISSUE TITLE
Ajustar exibição dos artigos para a visualização em "grade"

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#5]
Os artigos estão sendo exibidos um ao lado do outro, deixando o resto da tela sem conteúdo/em branco. Não seria uma opção exibi-los um abaixo do outro?
![screenshot_2016-01-29-11-19-40-1](https://cloud.githubusercontent.com/assets/5446933/12677060/8c33eb4c-c67d-11e5-97ef-d773c61a74ab.png)

**Comment by fabiobatalha** [comment]
@amandasramalho 

Essa foi uma decisão de design definida na concepção do aplicativo.

Esse comportamento é necessário pois o usuário pode escolher mais de um periódico para acompanhar.

Inclua pelo menos uns 6 periódicos em sua lista e verá o resultado.

**Comment by amandasramalho** [comment]
@fabiobatalha 

Entendi. É verdade, obrigada!
