### ISSUE TITLE
Data de publicação errada

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#6]
No aplicativo a data de publicação apresentada não esta de acordo com a data de publicação do documento. 

Verificando artigo Futebol, clãs e nação.
Data no Aplicativo: 1999
Data correta: 2000

![img_1506](https://cloud.githubusercontent.com/assets/504142/12676660/1054eb22-c67b-11e5-8b26-c3aead4427e5.PNG)

Artigo para conferência: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0011-52582000000100006&lang=pt

Resultado através de biblioteca Xylose a API:

```
 >>> import requests
 >>> from xylose.scielodocument import Article
 >>> at = requests.get('http://articlemeta.scielo.org/api/v1/article/?code=S0011-52582000000100006').json()
 >>> art = Article(at)
 >>> art.publication_date
 u'2000'
```

**Comment by mateusalmeida** [comment]
Acredito que o erro era causado por causa da time zone do brazil e acabava convertendo a data para outro dia

**Comment by fabiobatalha** [comment]
O problema foi corrigido onde?

**Comment by fabiobatalha** [comment]
O problema persiste.

**Comment by mateusalmeida** [comment]
Foi corrigido no github

No aplicativo gerado a partir do repositório já está apresentando a data correta

Aqui por exemplo está assim:

![screenshot_20160704-142953](https://cloud.githubusercontent.com/assets/10963190/16567801/15d4154c-41f9-11e6-8788-17c8f61043f1.png)

**Comment by mateusalmeida** [comment]
@fabiobatalha, poderia verificar se a data já está sendo exibida corretamente

**Comment by fabiobatalha** [comment]
@mateusalmeida 

Continua errado. Quando não existe dia e mês o mesmo não deve ser apresentado.

ex: 01-01 00:00

Deve ser apresentado somente o ano ou ano e mês quando presente.

**Comment by carlosecbraga** [comment]
Pessoal, foi feita uma alteração para correção desse problema. São necessárias:
1. Atualização no app;
2. Atualização das configurações do Solr (schema.xml e solrconfig.xml);
3. Atualização do harvest_job.py do pulsemob_webservices (ainda há um pull request pendente);
4. Limpeza dos documentos indexados no Solr e reindexação dos artigos.

**Comment by alexxxmendonca** [comment]
O problema persiste.

A maior parte dos registros estão exibindo a data como "undefined", apesar de termos a data de publicação e de entrada na base de todos os registros.

**Comment by carlosecbraga** [comment]
@fabiobatalha, após a atualização do código o problema foi resolvido mesmo?

**Comment by fabiobatalha** [comment]
@carlosecbraga A data esta presente na interface. Resta saber se o pessoal esta de acordo com a apresentação.

@alexxxmendonca você pode confirmar se esta ok.

**Comment by alexxxmendonca** [comment]
Testado e aprovado.
