### ISSUE TITLE
Artigos sem imagem de exibição

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/pulsemob_app#7]
![screenshot_2016-01-29-11-19-40-1](https://cloud.githubusercontent.com/assets/5446933/12677076/a9fa0b70-c67d-11e5-9067-2e8faf8a6c83.png)

**Comment by fabiobatalha** [comment]
@amandasramalho 

É porque o logo da revista é assim mesmo:

![screen shot 2016-01-29 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/504142/12682230/780b30be-c699-11e5-88ff-13da7ce2cf7b.png)
