### ISSUE TITLE
Resumo do artigo não é apresentado mesmo quando existe um disponível.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_app#9]
Ao acessar o artigo pelo aplicativo, reparei que o mesmo não possuía abstract na tela do documento.

Entretanto, avaliando os metadados é possível identificar a existência do abstract para um idioma diferente ao do idioma original do artigo:

![img_1507](https://cloud.githubusercontent.com/assets/504142/12677364/8d0c31f8-c67f-11e5-8a07-5d0e31e979e3.PNG)

Verificando metadados através de Xylose e API:

```
>>> import requests
>>> from xylose.scielodocument import Article
>>> at = requests.get('http://articlemeta.scielo.org/api/v1/article/?code=S0011-52582000000100003').json()
>>> art = Article(at)
>>> art.original_language()
u'pt'
>>> art.original_abstract()
>>> art.translated_abstracts()
{u'fr': u'Dans cet article on part des demandes de faveurs adress\xe9es \xe0 Rui Barbosa, \xe0 l\x92\xe9poque Ministre des Finances du gouvernement provisoire, pour examiner le sujet du client\xe9lisme dans la politique br\xe9silienne. On essaie de montrer la continuit\xe9 entre la monarchie et la r\xe9publique en ce qui concerne la domination des valeurs et pratiques client\xe9listes. On y soutient que le syst\xe8me de favoritisme, d\x92o\xf9 provient le client\xe9lisme, \xe9tait profond\xe9ment enracin\xe9 dans la soci\xe9t\xe9 qui, \xe0 son tour, le transposait \xe0 la politique. Par cons\xe9quent, les valeurs \xe9galitaires et la notion de chose publique, qui en principe devaient constituer la ligne d\x92action du nouveau r\xe9gime, ne trouvaient pas de terrain propice \xe0 leur d\xe9veloppement. Le citoyen devenait "Monsieur le citoyen", le politicien "cousin et ami".', u'en': u'In a discussion of the patron-client relation within Brazilian politics, the article takes as an example political favors asked of Rui Barbosa when he was the provisional government\x92s Minister of the Treasury. It endeavors to demonstrate how the prevalence of patron-client values and practices carried over from the monarchy to the Republic. The argument is posed that patronage, from which the patron-client relation derives, was deeply embedded in Brazilian society and from there moved into politics. As a consequence, egalitarian values and the notion of res publica, which in thesis should have been an integral part of the new regime\x92s practices, did not find propitious ground upon which to develop. Citizens became "doutor cidad\xe3o", while politicians became "cousin and friend".'}
```

**Comment by fabiobatalha** [comment]
@mateusalmeida Pergunta:

Bom dia, eu sou o Mateus e estou trabalhando nos erros do pulsemob_app, que estão abertos no github.
Eu estava vendo um não sabia direito o que fazer.

https://github.com/scieloorg/pulsemob_app/issues/9

Nesse caso o artigo não tem abstrac em português ou original_abstract, só tem o traduzido em inglês e francês. Se mudar o idioma para inglês o abstract é exibido.
Mas o que você queria dizer é que nesse caso por exemplo era pra usar o abstract em inglês mesmo com o idioma em português?

**Comment by fabiobatalha** [comment]
@mateusalmeida 

O idioma da interface pode ser considerado para priorizar a apresentação do abstract, mas nunca como fator limitador para apresentar o abstract quando este não existir no idioma da interface.

Neste caso você pode priorizar uma das traduções.

Pode considerar como prioridade os idiomas [pt, es, en, outros]

**Comment by mateusalmeida** [comment]
entendi, agora está mostrando quando um quando tem.

**Comment by fabiobatalha** [comment]
Aparentemente Ok para o registro mencionado.
